### ISSUE TITLE
Long max_wait_ns in jemalloc status.

### ISSUE THREAD

**Issue by sbvenkat** [jemalloc/jemalloc#1054]
Hi All,

Described this issue on gitter and as directed raising this question here. 

The actual problem:

We are using jemalloc version 5.0.1 in our multi-threaded file parsing application. In the process of improving our application throughput we noticed the below stack trace under gdb.
#0 lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135

#1 0x00007f0afdb91dbd in GI___pthread_mutex_lock (mutex=0x7f0ae985b568) at ../nptl/pthread_mutex_lock.c:80
#2 0x00007f0afe481088 in je_malloc_mutex_lock (mutex=0x7f0ae985b568) at include/jemalloc/internal/mutex.h:77
#3 je_tcache_bin_flush_small (tbin=0x7f0ab3806088, binind=3, rem=4, tcache=0x7f0ab3806000) at src/tcache.c:105
#4 0x00007f0afe481bfd in je_tcache_event_hard (tcache=0x7f0ab3806000) at src/tcache.c:39
#5 0x00007f0afe457104 in je_tcache_event (tcache=0x7f0ab3806000) at include/jemalloc/internal/tcache.h:271
#6 je_tcache_alloc_large (size=<optimized out>, tcache=<optimized out>, zero=<optimized out>) at include/jemalloc/internal/tcache.h:384
#7 je_arena_malloc (zero=false, size=<optimized out>, arena=0x0, try_tcache=true) at include/jemalloc/internal/arena.h:969
#8 je_imalloct (arena=0x0, try_tcache=true, size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:771
#9 je_imalloc (size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:780
#10 malloc (size=<optimized out>) at src/jemalloc.c:929

Later we noticed max_wait_ns value to be close to 0.3 seconds in jemalloc stats and this could be a potential problem for performance degradation. 
```
___ Begin jemalloc statistics ___
Version: 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb
Assertions disabled
config.malloc_conf: ""
Run-time option settings:
  opt.abort: false
  opt.abort_conf: false
  opt.retain: true
  opt.dss: "secondary"
  opt.narenas: 16
  opt.percpu_arena: "disabled"
  opt.background_thread: false (background_thread: false)
  opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
  opt.muzzy_decay_ms: 10000 (arenas.muzzy_decay_ms: 10000)
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.stats_print: true
  opt.stats_print_opts: ""
Arenas: 16
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Allocated: 9712028528, active: 9955016704, metadata: 66047272, resident: 10031435776, mapped: 10083471360, retained: 1786408960
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
background_thread:               2810               0               0            2123               0               0           0
ctl:                            76341             315               2            2108     12339917843       215998561           6
prof:                               0               0               0               0               0               0           0
Merged arenas stats:
assigned threads: 24
uptime: 389717405659
dss allocation precedence: N/A
decaying:  time       npages       sweeps     madvises       purged
   dirty:   N/A         2689         4411        18713       591223
   muzzy:   N/A            0            0            0            0
                            allocated      nmalloc      ndalloc    nrequests
small:                     2713926512    102075050     89041810   8310924619
large:                     6998102016       222174       166637       222174
total:                     9712028528    102297224     89208447   8311146793
active:                    9955016704
mapped:                   10083471360
retained:                  1786408960
base:                        65356320
internal:                      690952
tcache:                       3343072
resident:                 10031435776
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large:                         161184             417               0           44538     33959773925       271998189           1
extent_avail:                  407258               7               4           44551       127999148        67999548           1
extents_dirty:                2683031            2012              61           54134     94579370305       255998296           1
extents_muzzy:                 252944              19               1           40281               0               0           1
extents_retained:              480595              33               3           42893      1291991401       139999069           1
decay_dirty:                   170619               4               6           48972       335997762       119999201           1
decay_muzzy:                   156830               0               3           48940               0               0           0
base:                          319374               0               0           40081               0               0           0
tcache_list:                    44446               0               0           33755               0               0           0
bins:           size ind    allocated      nmalloc      ndalloc    nrequests      curregs     curslabs regs pgs  util       nfills     nflushes     newslabs      reslabs   n_lock_ops    n_waiting   n_spin_acq  total_wait_ns  max_wait_ns
                   8   0      9174768      4906777      3759931     36601392      1146846         2306  512   1 0.971      1004693       406832         4085       234510      1461810         2239           15   180946795463    467996886
                  16   1      7205120      4817615      4367295     32557685       450320         1822  256   1 0.965      2105395       415422         3099       549408      2569615         1948           24   154846969211    443997045
                  32   2    116546176     14673352     11031284    157879482      3642068        28549  128   1 0.996      3830591       663205        61628      1105934      4633249         3803           19   324037842967    367997551
                  48   3    119091024     21117092     18636029    146136133      2481063         9757  256   3 0.993      4776481       675422        31438       818636      5550373         2310           22   175370832583    387997418
                  64   4    173088448      8406224      5701717   3656045793      2704507        42320   64   1 0.998      2346330       478115        84551      1093944      2996245         1159           20    86831421953    351997657
                  80   5    128189680      6971937      5369566    106557284      1602371         6326  256   5 0.989      2639375       597101        11751       663173      3300550         1751           19   141603057405    379997470
                  96   6      3019200      3390002      3358552     23937634        31450          262  128   3 0.937      2327388       511514          346       687947      2884782          978           25    77851481768    283998109
                 112   7       269696       182457       180049      1175585         2408           15  256   7 0.627       176066        84788         1301         4039       307860          257            2    16923887325    199998668
                 128   8      2589824       261022       240789       447452        20233          663   32   1 0.953       200371        93323         2055        74910       342346          361           15    20267865081    255998296
                 160   9      1150880       102178        94985      3362154         7193           67  128   5 0.838        91210        45200          204        29311       181170          148            1     9171938926    127999148
                 192  10       229632        32430        31234      4559539         1196           35   64   3 0.533        11140         6582           52         2082        66033           96            3     3019979894    327997817
                 224  11     20437536       225910       134671      1162590        91239          729  128   7 0.977        52299        22166         1147        16553       120472           79            2     3583976143    111999255
                 256  12      3653888       130131       115858     13279718        14273          936   16   1 0.953        90379        33400         2894        65328       173060           93            4     4943967090    123999175
                 320  13      3213440       114813       104771     26059425        10042          182   64   5 0.862        95457        30952          240        36418       171252           40            2     2047986367    235998430
                 384  14       905856        22560        20201      1410778         2359           92   32   3 0.801        16780         6798          145         6921        68222           31            1     1295991369    127999148
                 448  15      1025024      1142867      1140579     50540401         2288           48   64   7 0.744       928728       455633           95       319196      1428922         1530            6   126807155844    375997497
                 512  16      1353728     34435026     34432382   3395765781         2644          377    8   1 0.876      3476467      3446590       770446     18050069      8507991         1339           37    81695456124    199998668
                 640  17      1716480         7842         5160      2634044         2682          104   32   5 0.805         2258         1301          156          544        48186           12            2      499996672    131999121
                 768  18      1994496         7740         5143      6693346         2597          183   16   3 0.886         2878         1693          323          629        49453           20            0      575996164    115999227
                 896  19      1291136         7314         5873    270189198         1441           65   32   7 0.692         3130         1769           97          991        49449           20            1      611995925    111999254
                1024  20     14321664       190116       176130     21647683        13986         3560    4   1 0.982       118507        21516        23534        69129       228861          476           17    13303911434    375997498
                1280  21     25966080        50427        30141     44317280        20286         1291   16   5 0.982         8026         2866         2609         2081        59238           20            0      447997016     55999627
                1536  22      7971840        17197        12007        44602         5190          689    8   3 0.941         5572         2605         1404         3909        55584          160            6     3507976648    127999148
                1792  23      6228992        37802        34326       191055         3476          247   16   7 0.879        32107        30131          385         1154       107241          165            0    12707915409    251998323
                2048  24     18716672        17880         8741       204504         9139         4590    2   1 0.995         6315         3215         7715         3101        64821           20            0      655995630     59999601
                2560  25   1888980480       744621         6738      5536396       737883        92250    8   5 0.999       279834         1608        92822          991       419264          398            5    15515896716    131999121
                3072  26     14505984         9670         4948     20025486         4722         1220    4   3 0.967         2709         1411         2005         1061        51334           22            2      535996433    111999254
                3584  27      7741440         5297         3137      2398773         2160          306    8   7 0.882         1847          841          487          676        47777           11            0      355997631     91999387
                4096  28     12161024         8915         5946    270301101         2969         2969    1   1 1             3838         2321         8915            0        65444           26            0      651995660     63999574
                5120  29     14402560         7441         4628        21996         2813          754    4   5 0.932         3289         1946         1189         1185        51282           65            5     1255991640    127999148
                6144  30     13910016         4551         2287        13466         2264         1164    2   3 0.972         1351          563         2031          506        49239            9            0      443997042     91999388
                7168  31     12350464         4218         2495        10929         1723          471    4   7 0.914         1303          545          841          694        47484            8            0      347997685    111999255
                8192  32     17301504         9633         7521      9182132         2112         2112    1   2 1             6583         5561         9633            0        73718           60            1     2635982456    119999202
               10240  33     23541760         4836         2537        13072         2299         1184    2   5 0.970         1797          798         2000          699        49865           21            2     1027993156    119999201
               12288  34     19795968         3673         2062        10838         1611         1611    1   3 1             1412          505         3673            0        52073            6            0       91999387     59999600
               14336  35     19884032         3484         2097         9892         1387          722    2   7 0.960         1439          608         1484          593        48712           17            0      159998934     35999761
large:          size ind    allocated      nmalloc      ndalloc    nrequests  curlextents
               16384  36     30670848       118412       116540       129671         1872
               20480  37     32071680         3309         1743        10069         1566
               24576  38     15704064         1845         1206        19239          639
               28672  39     24457216         1965         1112         7376          853
               32768...
```

**Comment by davidtgoldblatt** [comment]
Could you post the malloc stats to a github gist maybe? It looks like the bottom text got cut off.

**Comment by davidtgoldblatt** [comment]
One thing that jumps out at me is that there's a lot of time being spent on the lock guarding the mallctl interface. Could you describe a little bit what sorts of mallctl calls you're making? I wouldn't be surprised if they were related.

**Comment by sbvenkat** [comment]
[jemalloc_run_3.txt](https://github.com/jemalloc/jemalloc/files/1393126/jemalloc_run_3.txt)

**Comment by sbvenkat** [comment]
We couldn't collect the stats through opt.stats_print as our process crashed upon graceful shutdown. 

So we added an interface to call malloc_stats_print via command line. Other than that we are not making any mallctl calls in our application. Is it because of "malloc_stats_print" ?

**Comment by davidtgoldblatt** [comment]
Probably not; but it looks like the ctl mutex had 76,341 lock operations on it (and there's roughly one ctl lock acquisition per mallctl); is this expected?

Another thing that jumps out at me: it looks like you have in the thousands of threads (the bin locks in the arenas show hundreds of threads waiting on them at a time). Is this right? It's possible that you're just seeing run of the mill lock contention caused by threads getting descheduled while holding a lock.

One thing you could try if that's the issue is increasing the number of arenas. The easiest way to do this is to start your program with MALLOC_CONF="narenas:128" (or whatever other number you'd like to test) in the environment.

Could you describe a little more what sorts of activities your program does?

**Comment by davidtgoldblatt** [comment]
(Maybe the ctl acquisitions could be because of forking?)

**Comment by sbvenkat** [comment]
We weren't aware of ctl mutex until we looked at the stats. No where in our application we do any mallctl call. 

Initially we didn't set the arenas it was default(64: we have a 16 core cpu). We decreased the number of arenas thinking it would improve but no luck. 

We do not have thousands of threads. Are you referring to the n_waiting field ?  I can only think of the third-party libraries which we use in our application to cause those many number of threads. I got to do some digging on these libraries. 

About our application:
There are 26 threads, 16 threads are the actual service threads and rest are interfaces. Each service thread receives a file for some file scanning operation, completes the scan and returns the response back to the client. 

I will set the arenas to 128 and try

**Comment by davidtgoldblatt** [comment]
One way to verify the thread counts we're seeing is to take a look at /proc/<pid>/task and count the threads listed there.

**Comment by sbvenkat** [comment]
We verified form /proc, there are only 25 threads. Also our none of third-party libraries are creating threads. 

Wanted to know why you were suspecting thousands of threads ? Is it because of n_waiting ?

**Comment by sbvenkat** [comment]
We notice the below in stats summary.

                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large:                         161184             417               0           44538     33959773925       271998189           1
extent_avail:                  407258               7               4           44551       127999148        67999548           1
extents_dirty:                2683031            2012              61           54134     94579370305       255998296           1
extents_muzzy:                 252944              19               1           40281               0               0           1
extents_retained:              480595              33               3           42893      1291991401       139999069           1
decay_dirty:                   170619               4               6           48972       335997762       119999201           1

Is this something we can tune and reduce the wait time : extents_dirty ?

**Comment by davidtgoldblatt** [comment]
Yeah, it's n_waiting. @interwq, is there something that could cause n_waiting to be high without lots of threads?

**Comment by interwq** [comment]
Most contention is still from the bin locks. The application is very malloc intensive (has ~21M malloc operations per second). @sbvenkat: setting the higher number of arenas should solve this for you (actually using the default should be good since # of threads isn't that high here).

**Comment by davidtgoldblatt** [comment]
Ohhh, I had mixed up n_waiting and max_n_thds. Apologies, I should have checked before saying so.

**Comment by davidtgoldblatt** [comment]
That still doesn't explain the mallctl lock contention though. Could you clarify if you're doing lots of forking or something? (Or if you're getting malloc stats often)?

**Comment by sbvenkat** [comment]
@interwq attaching the stats which i dumped now. Our application has been running for 18 hours before i took these stats with default arena settings. The max_wait_ns is close to 1.5sec for 64 bin now. Increasing the arenas beyond default setting will reduce wait time ?
[jemalloc_stats_1019.txt](https://github.com/jemalloc/jemalloc/files/1399555/jemalloc_stats_1019.txt)

Just to confirm : Total malloc per second = (Sum of nmalloc) / uptime ?

@davidtgoldblatt 
Third-party library does some forking though not frequently. We can disable fork and collect stats. How would it help to reduce the mallctl lock contention ?

**Comment by davidtgoldblatt** [comment]
Really, I'm just trying to figure out what screwy thing is happening. The mallctl mutex is being acquired a lot of times, and seeing a lot of contention, which I wouldn't expect from a mutex that's only held during some manual stats printing.

The only other reason I can think of why it would get acquired is during forking (when we acquire all the mutexes we know about in our prefork handler). So I'm trying to see if forking behavior could be implemented.

But yeah, as Qi mentioned, upping the number of arenas should be your first bet if you see lock contention.

**Comment by interwq** [comment]
From the stats, the application has producer-consumer model -- looking at arena64 and beyond (which are manual arenas), they all have 1 thread per arena but a lot of lock contention.

I suspect the manual arenas are accessed somehow with TCACHE_NONE. @sbvenkat : you probably want to check the program to see if tcache is explicitly disabled or bypassed somehow for these arenas.

**Comment by sbvenkat** [comment]
@davidtgoldblatt we will disable forking in third-party library and check if it helps. We just collect stats only once to analyze and share with you folks, so we can ignore manual printing.

**Comment by sbvenkat** [comment]
@interwq how can we check from within the program if tcache is disabled. Is there an api which gives the tcache status or through gdb ?

**Comment by davidtgoldblatt** [comment]
tcache being disabled would show up in the malloc options, unless someone calls special jemalloc functions explicitly.

Does one of the libraries you link against possibly have some way of detecting if jemalloc is present, and altering behavior based on that? In the stats dump you posted, there are 14 arenas that were manually created, which should only happen if someone is making mallctl calls.

**Comment by interwq** [comment]
re: tcache -- yes it can still be disabled on a per thread basis, or with mallocx calls. From the stats, n_requests / n_lock_ops looks quite low, e.g. for arena 64 we have 1 lock for about every 10-20 requests, which is too small for the typical batch size we have seen (~50 or so). I suggest grep your code base and look for ```MALLOCX_TCACHE_NONE```, and any ```mallctl``` with ```tcache``` keyword.

**Comment by sbvenkat** [comment]
@interwq and @davidtgoldblatt 
Sorry about the delay in responding(had some production issue to take care). 

We were experimenting with arenas creation and those 14 manual arenas in the previous stats I provided were due to that. I will get rid of those manual arenas and collect stats with default arenas. 

We tried to stop forking child process within the 3-party library but were unsuccessful in doing so.

**Comment by davidtgoldblatt** [comment]
Could you also try to measure how often you're forking (and perhaps fork latency)? Those numbers might be informative as well.

**Comment by interwq** [comment]
Feel free to let us know if any questions.

**Comment by justmao945** [comment]
[jemalloc.txt](https://github.com/jemalloc/jemalloc/files/3280104/jemalloc.txt)

Same situation here. 
We use jemalloc 5.2.0 on  64C 128G machine.
We have fixed thread pool with 64 threads to do heavy caculation & memory allocation.
The problem is that we can not improve the CPU usage (sometimes about 50% usage) even all 64 threads are ocuppied.
And the max_wait_ns seems too long, some bin exceeds 1s.
So does this situation hit the bottleneck of jemalloc ? We are writing request/session level memory pool to decrease the presure of jemalloc.
