### ISSUE TITLE
Make less modest use of mmap(2)

### ISSUE THREAD

**Issue by trasz** [jemalloc/jemalloc#1339]
As it is now (at least under FreeBSD), jemalloc likes to do stuff like so:

```
mmap(0x8013a1000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380320768 (0x8013a1000)                                                                                         
mmap(0x8013a2000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380324864 (0x8013a2000)
mmap(0x8013a3000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380328960 (0x8013a3000)
mmap(0x8013a4000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380333056 (0x8013a4000)                                                                                         
mmap(0x8013a6000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380341248 (0x8013a6000)                                                                                         
mmap(0x8013a8000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380349440 (0x8013a8000)
mmap(0x8013aa000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380357632 (0x8013aa000)
```

So, it does a lot of small allocations one after another, instead of being more greedy and using larger mmap sizes.  Is there a reason for doing it like this?  This adds quite some overhead, syscall-wise.

**Comment by interwq** [comment]
Enabling `opt.retain` should solve this (madvised instead of munmap will be used; plus a increasingly larger sequence is used to grow the VM space). Adding "retain:true" to the malloc_conf will enable the option (it's enabled on Linux, see http://jemalloc.net/jemalloc.3.html#opt.retain for details).

**Comment by trasz** [comment]
Hm, it doesn't seem to change the situation: I'm still seeing o lot of stuff like this:

```
4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367180800 (0x800719000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367188992 (0x80071b000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367197184 (0x80071d000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367295488 (0x800735000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367303680 (0x800737000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367311872 (0x800739000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367320064 (0x80073b000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367328256 (0x80073d000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367336448 (0x80073f000)
 4930: mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367344640 (0x800741000)
 4930: mmap(0x0,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367352832 (0x800743000)
 4930: mmap(0x0,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367365120 (0x800746000)
 4930: mmap(0x0,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367377408 (0x800749000)
 4930: mmap(0x0,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367389696 (0x80074c000)
 4930: mmap(0x0,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367401984 (0x80074f000)
 4930: mmap(0x0,20480,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367414272 (0x800752000)
 4930: mmap(0x0,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367205376 (0x80071f000)
 4930: mmap(0x0,20480,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367434752 (0x800757000)
 4930: mmap(0x0,20480,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34367455232 (0x80075c000)
```

Note that I don't see pretty much any munmaps - this is all about allocating memory shortly after startup, in short-running processes - in FreeBSD jemalloc is the system malloc.

**Comment by trasz** [comment]
FWIW, sample backtraces can be found here: https://gist.github.com/trasz/14d62531528f117fa13d99f5f0228e68

**Comment by interwq** [comment]
As mentioned in #1350, `retain:true` solves this (i.e. reduces # of syscalls). @trasz will help to run some benchmark and we'll discuss if it should be default on for FreeBSD as well.

**Comment by interwq** [comment]
@trasz, as the `retain` option is fixed in #1350, also it has been the default on Linux for a long time, any insights on whether it should be the default on FreeBSD as well? The main concern is probably the VM size. However the `mmap` / `munmap` pairs avoided (or rather replaced with `madvise`) might make it a worth while tradeoff.

Based on the questions we get regarding the VM size / retain, it may cause some confusion as well (it could well be the real concern). I'm inclined to say not flipping the switch unless we get some compelling reason / data to justify. cc: @jasone

**Comment by jasone** [comment]
Did we ever discuss whether `retain` should have a different default for 32-bit vs 64-bit systems?  I worry that we'll exacerbate address space issues for 32-bit platforms, but for 64-bit platforms I know of no reason FreeBSD should be treated any differently than Linux.

**Comment by interwq** [comment]
@jasone : yes we did. Agree that VM exhaustion is a real concern on 32-bit. Retain is currently only enabled on 64 bit Linux based platforms, https://github.com/jemalloc/jemalloc/blob/dev/configure.ac#L666

**Comment by trasz** [comment]
FWIW, worldbench on 72 threads (POWER) doesn't show any regression (thanks to jhibbits@ for checking this).
