### ISSUE TITLE
Unrealistic value of "Current active ceiling"

### ISSUE THREAD

**Issue by rustyx** [jemalloc/jemalloc#336]
"Current active ceiling" is sometimes reporting very high values on Windows x64.

In the example below the reported value is 18446744073682223104, or 0xFFFFFFFFFE5F000, suggesting a negative overflow.

Happens mostly after a large deallocation (~10GB worth of objects), could be a race in the stats processing.

```
___ Begin jemalloc statistics ___
Version: 4.0.4-24-gbfe5110792cea00124ba46c58bd474dc662bfa33
Assertions disabled
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 16
  opt.dss: "secondary"
  opt.narenas: 128
  opt.lg_dirty_mult: 3 (arenas.lg_dirty_mult: 3)
  opt.stats_print: false
  opt.junk: "false"
  opt.quarantine: 0
  opt.redzone: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
CPUs: 32
Arenas: 138
Pointer size: 8
Quantum size: 16
Page size: 4096
Min active:dirty page ratio per arena: 8:1
Maximum thread-cached size class: 32768
Chunk size: 65536 (2^16)
Allocated: 6930424, active: 10821632, metadata: 7139456, resident: 17084416, mapped: 26869760
Current active ceiling: 18446744073682223104

Merged arenas stats:
assigned threads: 14
dss allocation precedence: N/A
min active:dirty page ratio: N/A
dirty pages: 2642:166 active:dirty, 441542 sweeps, 848891 madvises, 18941792 purged
                            allocated      nmalloc      ndalloc    nrequests
small:                        3092472     62504775     62495574   1581764484
large:                         692224        79930        79906       175878
huge:                         3145728       573399       573381       573399
total:                        6930424     63158104     63148861   1582513761
active:                      10821632
mapped:                      22478848
metadata: mapped: 1208320, allocated: 1560064
. . .
```

**Comment by jasone** [comment]
My first guess is that chunk deallocations are being subtracted twice due to some aspect of chunk decommit logic, which is only used on Windows.

**Comment by yuslepukhin** [comment]
@rustyx number of places where we cast 64-bit to int and long that are 32-bit. I can spend time and present a PR with fixed warnings. Would this be of value?

**Comment by jasone** [comment]
I fixed a bunch of warnings for #317, but didn't specifically see any issues that would explain the active ceiling underflow.

**Comment by rustyx** [comment]
I doubt that this is related to a 32-bit overflow, otherwise the value would have been around -4GB, but is just -1.7MB. Nevertheless, will test the fixes...

**Comment by rustyx** [comment]
With the current dev branch I can still reproduce the issue even with simple test_threads app.

Is definitely a race. Single-threaded the value is stable at 65536, with 2 threads it begins to fluctuate between 65536 and 131072, with 4 threads it's all over the place: 65536, 0, 18446744073709092864.

Examples: [1](http://rustyx.org/temp/jemalloc-336/1.txt), [2](http://rustyx.org/temp/jemalloc-336/2.txt), [3](http://rustyx.org/temp/jemalloc-336/3.txt), [4](http://rustyx.org/temp/jemalloc-336/4.txt), [5](http://rustyx.org/temp/jemalloc-336/5.txt), [6](http://rustyx.org/temp/jemalloc-336/6.txt), [7](http://rustyx.org/temp/jemalloc-336/7.txt).

**Comment by jasone** [comment]
I audited the cactive code, and the only thing I found was 3763d3b5f92d855596e111a339c1fa9583c4602a, which could be the problem.  Unfortunately, I was unable to run the test_threads app, since I only have MSVC++ 2013, which apparently can't build the project.

**Comment by rustyx** [comment]
I can reproduce the same issue on FreeBSD.
When chunk size is 64KB (same as the default on Windows), the issue also occurs on BSD.
[This script](rustyx.org/temp/jemalloc-336/test-336.sh) will demonstrate the issue (after merging pull request #344, which makes test_threads compile on clang).

**Comment by jasone** [comment]
Thanks @rustyx, the problem reproduces for me on FreeBSD.  I'll dig into it today.
